#!/bin/bash
# =============================================================================
# PROJECT ZEAL – SAFE GIT PUSH TO ORIGIN
# =============================================================================
# This script safely pushes all changes to the remote repository.
# It performs:
#   1. Check for uncommitted changes
#   2. Stage all changes (including new files)
#   3. Commit with a detailed message
#   4. Pull latest from origin to avoid merge conflicts
#   5. Push to origin
# =============================================================================

set -euo pipefail

echo "🔐 Preparing to push all changes to origin safely..."

# ----------------------------------------------------------------------------
# 1. Check Git status
# ----------------------------------------------------------------------------
echo ""
echo "📋 Current Git status:"
git status --short

# ----------------------------------------------------------------------------
# 2. Ensure we're on the correct branch
# ----------------------------------------------------------------------------
BRANCH=$(git branch --show-current)
echo ""
echo "📍 Current branch: $BRANCH"
read -p "Is this the correct branch to push from? (y/n) " -n 1 -r
echo ""
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "❌ Please switch to the correct branch and run again."
    exit 1
fi

# ----------------------------------------------------------------------------
# 3. Add all changes
# ----------------------------------------------------------------------------
echo ""
echo "📦 Staging all changes..."
git add -A
git status --short

# ----------------------------------------------------------------------------
# 4. Commit changes
# ----------------------------------------------------------------------------
COMMIT_MESSAGE="🚀 Project Zeal: Complete Admin App & Real-time Features

This commit includes:
- Admin app fully functional with real‑time WebSocket integration
- Production‑ready admin pages: Dashboard, Bookings, Recordings, Wallet
- Full‑screen alert overlay for incoming chat/call/booking
- Premium glassmorphism UI/UX, mobile‑first design
- Supabase authentication and role‑based access (Super Admin / Client Admin)
- Real‑time notifications, connection status indicator
- Recording management with auto‑delete after 12h
- Wallet top‑up and transaction history (Super Admin)
- All pages are enterprise‑grade with error handling
- Proxy.ts fixed for Next.js 16 compatibility
- ClerkProvider added to admin root layout

Generated by Project Zeal Admin App setup."

echo ""
echo "📝 Commit message:"
echo "$COMMIT_MESSAGE"
echo ""
read -p "Proceed with this commit? (y/n) " -n 1 -r
echo ""
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "❌ Commit cancelled."
    exit 1
fi

git commit -m "$COMMIT_MESSAGE"

# ----------------------------------------------------------------------------
# 5. Pull latest from origin to avoid conflicts
# ----------------------------------------------------------------------------
echo ""
echo "⬇️ Pulling latest changes from origin/$BRANCH..."
if git pull origin "$BRANCH" --no-edit; then
    echo "✅ Pull successful."
else
    echo "⚠️ Pull failed. There might be conflicts."
    echo "Please resolve conflicts manually and run: git push origin $BRANCH"
    exit 1
fi

# ----------------------------------------------------------------------------
# 6. Push to origin
# ----------------------------------------------------------------------------
echo ""
echo "⬆️ Pushing to origin/$BRANCH..."
if git push origin "$BRANCH"; then
    echo ""
    echo "✅ Push successful!"
    echo "🔗 Your changes are now on origin/$BRANCH."
else
    echo "❌ Push failed. Please check your network or permissions."
    exit 1
fi

# ----------------------------------------------------------------------------
# 7. Final status
# ----------------------------------------------------------------------------
echo ""
echo "📋 Final Git status:"
git status

echo ""
echo "🎉 All changes pushed safely to origin!"
echo "You can now deploy or continue development."