import { NextResponse } from 'next/server';
import { withErrorHandler } from '@/lib/errors';

// Mock data – replace with DB query
const consultants = [
  // Astrologers
  { id: 'ai1', name: 'AstroAI-1', username: 'astroai1', avatar: 'https://ui-avatars.com/api/?name=AI+1&background=533AFD&color=fff', category: 'ASTROLOGER', specialties: ['Vedic', 'KP'], isPaid: false, perMinuteRate: 0, rating: 4.8, totalConsultations: 5000, bio: 'Vedic Astrologer with AI precision.', isOnline: true, languages: ['English'] },
  { id: 'ai2', name: 'AstroAI-2', username: 'astroai2', avatar: 'https://ui-avatars.com/api/?name=AI+2&background=533AFD&color=fff', category: 'ASTROLOGER', specialties: ['Nadi', 'Muhurtha'], isPaid: false, perMinuteRate: 0, rating: 4.7, totalConsultations: 4000, bio: 'Nadi expert powered by AI.', isOnline: true, languages: ['English'] },
  { id: 'ai3', name: 'AstroAI-3', username: 'astroai3', avatar: 'https://ui-avatars.com/api/?name=AI+3&background=533AFD&color=fff', category: 'ASTROLOGER', specialties: ['Western', 'KP'], isPaid: true, perMinuteRate: 5, rating: 4.9, totalConsultations: 6000, bio: 'Premium AI Vedic Astrologer.', isOnline: true, languages: ['English'] },
  { id: 'ai4', name: 'AstroAI-4', username: 'astroai4', avatar: 'https://ui-avatars.com/api/?name=AI+4&background=533AFD&color=fff', category: 'ASTROLOGER', specialties: ['Vedic', 'Nadi'], isPaid: true, perMinuteRate: 8, rating: 4.9, totalConsultations: 7000, bio: 'Advanced AI Nadi astrologer.', isOnline: true, languages: ['English'] },
  // Psychologists (5)
  { id: 'ps1', name: 'PsychAI-1', username: 'psychai1', avatar: 'https://ui-avatars.com/api/?name=PsychAI-1&background=533AFD&color=fff', category: 'PSYCHOLOGIST', specialties: ['CBT', 'Anxiety'], isPaid: false, perMinuteRate: 0, rating: 4.6, totalConsultations: 3000, bio: 'AI CBT therapist.', isOnline: true, languages: ['English'] },
  { id: 'ps2', name: 'PsychAI-2', username: 'psychai2', avatar: 'https://ui-avatars.com/api/?name=PsychAI-2&background=533AFD&color=fff', category: 'PSYCHOLOGIST', specialties: ['Depression', 'Mindfulness'], isPaid: false, perMinuteRate: 0, rating: 4.5, totalConsultations: 2800, bio: 'AI Mindfulness coach.', isOnline: true, languages: ['English'] },
  { id: 'ps3', name: 'PsychAI-3', username: 'psychai3', avatar: 'https://ui-avatars.com/api/?name=PsychAI-3&background=533AFD&color=fff', category: 'PSYCHOLOGIST', specialties: ['Trauma', 'CBT'], isPaid: true, perMinuteRate: 6, rating: 4.8, totalConsultations: 4000, bio: 'Premium AI trauma therapist.', isOnline: true, languages: ['English'] },
  { id: 'ps4', name: 'PsychAI-4', username: 'psychai4', avatar: 'https://ui-avatars.com/api/?name=PsychAI-4&background=533AFD&color=fff', category: 'PSYCHOLOGIST', specialties: ['Anxiety', 'Mindfulness'], isPaid: true, perMinuteRate: 7, rating: 4.7, totalConsultations: 3500, bio: 'Advanced AI anxiety specialist.', isOnline: true, languages: ['English'] },
  // Tarot (5)
  { id: 't1', name: 'TarotAI-1', username: 'tarotai1', avatar: 'https://ui-avatars.com/api/?name=TarotAI-1&background=533AFD&color=fff', category: 'TAROT', specialties: ['Rider-Waite', 'Lenormand'], isPaid: false, perMinuteRate: 0, rating: 4.6, totalConsultations: 4000, bio: 'AI Rider-Waite tarot reader.', isOnline: true, languages: ['English'] },
  { id: 't2', name: 'TarotAI-2', username: 'tarotai2', avatar: 'https://ui-avatars.com/api/?name=TarotAI-2&background=533AFD&color=fff', category: 'TAROT', specialties: ['Osho Zen', 'Angel Cards'], isPaid: false, perMinuteRate: 0, rating: 4.5, totalConsultations: 3500, bio: 'AI intuitive tarot reader.', isOnline: true, languages: ['English'] },
  { id: 't3', name: 'TarotAI-3', username: 'tarotai3', avatar: 'https://ui-avatars.com/api/?name=TarotAI-3&background=533AFD&color=fff', category: 'TAROT', specialties: ['Marseille', 'Rider-Waite'], isPaid: true, perMinuteRate: 6, rating: 4.9, totalConsultations: 5000, bio: 'Premium AI tarot master.', isOnline: true, languages: ['English'] },
  { id: 't4', name: 'TarotAI-4', username: 'tarotai4', avatar: 'https://ui-avatars.com/api/?name=TarotAI-4&background=533AFD&color=fff', category: 'TAROT', specialties: ['Lenormand', 'Angel Cards'], isPaid: true, perMinuteRate: 7, rating: 4.8, totalConsultations: 4500, bio: 'Advanced AI Lenormand reader.', isOnline: true, languages: ['English'] },
  // Numerologists (5)
  { id: 'n1', name: 'NumerAI-1', username: 'numerai1', avatar: 'https://ui-avatars.com/api/?name=NumerAI-1&background=533AFD&color=fff', category: 'NUMEROLOGIST', specialties: ['Chaldean', 'Pythagorean'], isPaid: false, perMinuteRate: 0, rating: 4.5, totalConsultations: 3000, bio: 'AI Chaldean numerologist.', isOnline: true, languages: ['English'] },
  { id: 'n2', name: 'NumerAI-2', username: 'numerai2', avatar: 'https://ui-avatars.com/api/?name=NumerAI-2&background=533AFD&color=fff', category: 'NUMEROLOGIST', specialties: ['Kabbalah', 'Indian'], isPaid: false, perMinuteRate: 0, rating: 4.4, totalConsultations: 2800, bio: 'AI Kabbalah numerologist.', isOnline: true, languages: ['English'] },
  { id: 'n3', name: 'NumerAI-3', username: 'numerai3', avatar: 'https://ui-avatars.com/api/?name=NumerAI-3&background=533AFD&color=fff', category: 'NUMEROLOGIST', specialties: ['Pythagorean', 'Chinese'], isPaid: true, perMinuteRate: 5, rating: 4.8, totalConsultations: 4000, bio: 'Premium AI numerologist.', isOnline: true, languages: ['English'] },
  { id: 'n4', name: 'NumerAI-4', username: 'numerai4', avatar: 'https://ui-avatars.com/api/?name=NumerAI-4&background=533AFD&color=fff', category: 'NUMEROLOGIST', specialties: ['Chaldean', 'Kabbalah'], isPaid: true, perMinuteRate: 6, rating: 4.7, totalConsultations: 3800, bio: 'Advanced AI numerologist.', isOnline: true, languages: ['English'] },
  // Palmists (5)
  { id: 'p1', name: 'PalmAI-1', username: 'palmai1', avatar: 'https://ui-avatars.com/api/?name=PalmAI-1&background=533AFD&color=fff', category: 'PALMIST', specialties: ['Classical', 'Modern'], isPaid: false, perMinuteRate: 0, rating: 4.5, totalConsultations: 2000, bio: 'AI palmist for classical readings.', isOnline: true, languages: ['English'] },
  { id: 'p2', name: 'PalmAI-2', username: 'palmai2', avatar: 'https://ui-avatars.com/api/?name=PalmAI-2&background=533AFD&color=fff', category: 'PALMIST', specialties: ['Modern', 'Psychological'], isPaid: false, perMinuteRate: 0, rating: 4.4, totalConsultations: 1800, bio: 'AI modern palmist.', isOnline: true, languages: ['English'] },
  { id: 'p3', name: 'PalmAI-3', username: 'palmai3', avatar: 'https://ui-avatars.com/api/?name=PalmAI-3&background=533AFD&color=fff', category: 'PALMIST', specialties: ['Classical', 'Psychological'], isPaid: true, perMinuteRate: 5, rating: 4.8, totalConsultations: 3000, bio: 'Premium AI palmist.', isOnline: true, languages: ['English'] },
  { id: 'p4', name: 'PalmAI-4', username: 'palmai4', avatar: 'https://ui-avatars.com/api/?name=PalmAI-4&background=533AFD&color=fff', category: 'PALMIST', specialties: ['Modern', 'Classical'], isPaid: true, perMinuteRate: 6, rating: 4.7, totalConsultations: 2800, bio: 'Advanced AI palmist.', isOnline: true, languages: ['English'] },
  // Vastu (5)
  { id: 'v1', name: 'VastuAI-1', username: 'vastuai1', avatar: 'https://ui-avatars.com/api/?name=VastuAI-1&background=533AFD&color=fff', category: 'VASTU', specialties: ['Vastu Shastra', 'Feng Shui'], isPaid: false, perMinuteRate: 0, rating: 4.6, totalConsultations: 2500, bio: 'AI Vastu consultant.', isOnline: true, languages: ['English'] },
  { id: 'v2', name: 'VastuAI-2', username: 'vastuai2', avatar: 'https://ui-avatars.com/api/?name=VastuAI-2&background=533AFD&color=fff', category: 'VASTU', specialties: ['Feng Shui', 'Vastu Shastra'], isPaid: false, perMinuteRate: 0, rating: 4.5, totalConsultations: 2300, bio: 'AI Feng Shui expert.', isOnline: true, languages: ['English'] },
  { id: 'v3', name: 'VastuAI-3', username: 'vastuai3', avatar: 'https://ui-avatars.com/api/?name=VastuAI-3&background=533AFD&color=fff', category: 'VASTU', specialties: ['Vastu Shastra', 'Feng Shui'], isPaid: true, perMinuteRate: 6, rating: 4.9, totalConsultations: 3500, bio: 'Premium AI Vastu consultant.', isOnline: true, languages: ['English'] },
  { id: 'v4', name: 'VastuAI-4', username: 'vastuai4', avatar: 'https://ui-avatars.com/api/?name=VastuAI-4&background=533AFD&color=fff', category: 'VASTU', specialties: ['Feng Shui', 'Vastu Shastra'], isPaid: true, perMinuteRate: 7, rating: 4.8, totalConsultations: 3200, bio: 'Advanced AI Vastu expert.', isOnline: true, languages: ['English'] },
  // Reiki (5)
  { id: 'r1', name: 'ReikiAI-1', username: 'reikiai1', avatar: 'https://ui-avatars.com/api/?name=ReikiAI-1&background=533AFD&color=fff', category: 'REIKI', specialties: ['Reiki', 'Pranic'], isPaid: false, perMinuteRate: 0, rating: 4.6, totalConsultations: 3000, bio: 'AI Reiki healer.', isOnline: true, languages: ['English'] },
  { id: 'r2', name: 'ReikiAI-2', username: 'reikiai2', avatar: 'https://ui-avatars.com/api/?name=ReikiAI-2&background=533AFD&color=fff', category: 'REIKI', specialties: ['Crystal', 'Sound'], isPaid: false, perMinuteRate: 0, rating: 4.5, totalConsultations: 2800, bio: 'AI Crystal healer.', isOnline: true, languages: ['English'] },
  { id: 'r3', name: 'ReikiAI-3', username: 'reikiai3', avatar: 'https://ui-avatars.com/api/?name=ReikiAI-3&background=533AFD&color=fff', category: 'REIKI', specialties: ['Reiki', 'Energy'], isPaid: true, perMinuteRate: 6, rating: 4.9, totalConsultations: 4000, bio: 'Premium AI Reiki master.', isOnline: true, languages: ['English'] },
  { id: 'r4', name: 'ReikiAI-4', username: 'reikiai4', avatar: 'https://ui-avatars.com/api/?name=ReikiAI-4&background=533AFD&color=fff', category: 'REIKI', specialties: ['Pranic', 'Crystal'], isPaid: true, perMinuteRate: 7, rating: 4.8, totalConsultations: 3800, bio: 'Advanced AI Pranic healer.', isOnline: true, languages: ['English'] },
  // Life Coaches (5)
  { id: 'l1', name: 'CoachAI-1', username: 'coachai1', avatar: 'https://ui-avatars.com/api/?name=CoachAI-1&background=533AFD&color=fff', category: 'LIFE_COACH', specialties: ['Career', 'Relationships'], isPaid: false, perMinuteRate: 0, rating: 4.5, totalConsultations: 2000, bio: 'AI Career coach.', isOnline: true, languages: ['English'] },
  { id: 'l2', name: 'CoachAI-2', username: 'coachai2', avatar: 'https://ui-avatars.com/api/?name=CoachAI-2&background=533AFD&color=fff', category: 'LIFE_COACH', specialties: ['Health', 'Finance'], isPaid: false, perMinuteRate: 0, rating: 4.4, totalConsultations: 1800, bio: 'AI Health and Finance coach.', isOnline: true, languages: ['English'] },
  { id: 'l3', name: 'CoachAI-3', username: 'coachai3', avatar: 'https://ui-avatars.com/api/?name=CoachAI-3&background=533AFD&color=fff', category: 'LIFE_COACH', specialties: ['Personal Growth', 'Relationships'], isPaid: true, perMinuteRate: 5, rating: 4.8, totalConsultations: 3000, bio: 'Premium AI Life coach.', isOnline: true, languages: ['English'] },
  { id: 'l4', name: 'CoachAI-4', username: 'coachai4', avatar: 'https://ui-avatars.com/api/?name=CoachAI-4&background=533AFD&color=fff', category: 'LIFE_COACH', specialties: ['Career', 'Personal Growth'], isPaid: true, perMinuteRate: 6, rating: 4.7, totalConsultations: 2800, bio: 'Advanced AI Career and Growth coach.', isOnline: true, languages: ['English'] },
  // Healers (5)
  { id: 'h1', name: 'HealAI-1', username: 'healai1', avatar: 'https://ui-avatars.com/api/?name=HealAI-1&background=533AFD&color=fff', category: 'HEALER', specialties: ['Reiki', 'Pranic'], isPaid: false, perMinuteRate: 0, rating: 4.6, totalConsultations: 2500, bio: 'AI Energy healer.', isOnline: true, languages: ['English'] },
  { id: 'h2', name: 'HealAI-2', username: 'healai2', avatar: 'https://ui-avatars.com/api/?name=HealAI-2&background=533AFD&color=fff', category: 'HEALER', specialties: ['Crystal', 'Sound'], isPaid: false, perMinuteRate: 0, rating: 4.5, totalConsultations: 2300, bio: 'AI Sound healer.', isOnline: true, languages: ['English'] },
  { id: 'h3', name: 'HealAI-3', username: 'healai3', avatar: 'https://ui-avatars.com/api/?name=HealAI-3&background=533AFD&color=fff', category: 'HEALER', specialties: ['Reiki', 'Energy'], isPaid: true, perMinuteRate: 6, rating: 4.9, totalConsultations: 3500, bio: 'Premium AI Healer.', isOnline: true, languages: ['English'] },
  { id: 'h4', name: 'HealAI-4', username: 'healai4', avatar: 'https://ui-avatars.com/api/?name=HealAI-4&background=533AFD&color=fff', category: 'HEALER', specialties: ['Pranic', 'Crystal'], isPaid: true, perMinuteRate: 7, rating: 4.8, totalConsultations: 3200, bio: 'Advanced AI Healer.', isOnline: true, languages: ['English'] },
];

export const GET = withErrorHandler(async (req: Request) => {
  const url = new URL(req.url);
  const category = url.searchParams.get('category');
  let filtered = consultants;
  if (category) {
    filtered = consultants.filter(c => c.category === category);
  }
  return NextResponse.json(filtered);
});
