import { ConsultantCategory, Faith } from '@prisma/client';

export const consultants = [
  // Astrologers (5)
  {
    name: 'Rajesh Sharma',
    username: 'raj_astrologer',
    email: 'raj@zeal.com',
    category: ConsultantCategory.ASTROLOGER,
    specialties: ['Vedic', 'KP', 'Nadi'],
    languages: ['Hindi', 'English'],
    bio: 'Vedic Astrologer with 15+ years of experience. Specializing in career and relationships.',
    perMinuteRate: 75,
    faith: Faith.HINDU,
    availability: {
      monday: [{ start: '09:00', end: '18:00' }],
      tuesday: [{ start: '09:00', end: '18:00' }],
      wednesday: [{ start: '09:00', end: '18:00' }],
      thursday: [{ start: '09:00', end: '18:00' }],
      friday: [{ start: '09:00', end: '18:00' }],
      saturday: [{ start: '10:00', end: '14:00' }],
      sunday: [],
    },
  },
  {
    name: 'Priya Patel',
    username: 'priya_jyotish',
    email: 'priya@zeal.com',
    category: ConsultantCategory.ASTROLOGER,
    specialties: ['Vedic', 'Muhurtha'],
    languages: ['Hindi', 'English'],
    bio: 'Nadi astrologer with deep knowledge of planetary transits.',
    perMinuteRate: 60,
    faith: Faith.HINDU,
    availability: {
      monday: [{ start: '10:00', end: '19:00' }],
      tuesday: [{ start: '10:00', end: '19:00' }],
      wednesday: [{ start: '10:00', end: '19:00' }],
      thursday: [{ start: '10:00', end: '19:00' }],
      friday: [{ start: '10:00', end: '19:00' }],
      saturday: [{ start: '09:00', end: '13:00' }],
      sunday: [],
    },
  },
  {
    name: 'Amit Singh',
    username: 'amit_astrologer',
    email: 'amit@zeal.com',
    category: ConsultantCategory.ASTROLOGER,
    specialties: ['KP', 'Western'],
    languages: ['English'],
    bio: 'KP astrologer with 10+ years of experience.',
    perMinuteRate: 55,
    faith: Faith.HINDU,
    availability: {
      monday: [{ start: '08:00', end: '17:00' }],
      tuesday: [{ start: '08:00', end: '17:00' }],
      wednesday: [{ start: '08:00', end: '17:00' }],
      thursday: [{ start: '08:00', end: '17:00' }],
      friday: [{ start: '08:00', end: '17:00' }],
      saturday: [{ start: '10:00', end: '15:00' }],
      sunday: [],
    },
  },
  {
    name: 'Sana Khan',
    username: 'sana_astro',
    email: 'sana@zeal.com',
    category: ConsultantCategory.ASTROLOGER,
    specialties: ['Vedic', 'Nadi'],
    languages: ['Hindi', 'Urdu', 'English'],
    bio: 'Spiritual astrologer guiding life decisions through planetary wisdom.',
    perMinuteRate: 80,
    faith: Faith.ISLAM,
    availability: {
      monday: [{ start: '11:00', end: '20:00' }],
      tuesday: [{ start: '11:00', end: '20:00' }],
      wednesday: [{ start: '11:00', end: '20:00' }],
      thursday: [{ start: '11:00', end: '20:00' }],
      friday: [{ start: '11:00', end: '20:00' }],
      saturday: [{ start: '12:00', end: '16:00' }],
      sunday: [],
    },
  },
  {
    name: 'Vikram Rao',
    username: 'vikram_astro',
    email: 'vikram@zeal.com',
    category: ConsultantCategory.ASTROLOGER,
    specialties: ['Vedic', 'Muhurtha'],
    languages: ['Hindi', 'English'],
    bio: 'Vedic astrologer with expertise in timing events.',
    perMinuteRate: 70,
    faith: Faith.HINDU,
    availability: {
      monday: [{ start: '09:30', end: '18:30' }],
      tuesday: [{ start: '09:30', end: '18:30' }],
      wednesday: [{ start: '09:30', end: '18:30' }],
      thursday: [{ start: '09:30', end: '18:30' }],
      friday: [{ start: '09:30', end: '18:30' }],
      saturday: [{ start: '08:00', end: '12:00' }],
      sunday: [],
    },
  },
  // Psychologists (5)
  {
    name: 'Dr. Meera Nair',
    username: 'dr_meera',
    email: 'meera@zeal.com',
    category: ConsultantCategory.PSYCHOLOGIST,
    specialties: ['CBT', 'Anxiety', 'Depression'],
    languages: ['English', 'Malayalam'],
    bio: 'Licensed clinical psychologist with 12+ years of experience.',
    perMinuteRate: 100,
    faith: Faith.OTHER,
    availability: {
      monday: [{ start: '10:00', end: '18:00' }],
      tuesday: [{ start: '10:00', end: '18:00' }],
      wednesday: [{ start: '10:00', end: '18:00' }],
      thursday: [{ start: '10:00', end: '18:00' }],
      friday: [{ start: '10:00', end: '18:00' }],
      saturday: [{ start: '09:00', end: '13:00' }],
      sunday: [],
    },
  },
  {
    name: 'Dr. Arjun Gupta',
    username: 'dr_arjun',
    email: 'arjun@zeal.com',
    category: ConsultantCategory.PSYCHOLOGIST,
    specialties: ['Trauma', 'Mindfulness'],
    languages: ['Hindi', 'English'],
    bio: 'Psychologist specializing in trauma recovery and mindfulness.',
    perMinuteRate: 95,
    faith: Faith.HINDU,
    availability: {
      monday: [{ start: '09:00', end: '17:00' }],
      tuesday: [{ start: '09:00', end: '17:00' }],
      wednesday: [{ start: '09:00', end: '17:00' }],
      thursday: [{ start: '09:00', end: '17:00' }],
      friday: [{ start: '09:00', end: '17:00' }],
      saturday: [],
      sunday: [],
    },
  },
  {
    name: 'Dr. Ritu Sharma',
    username: 'dr_ritu',
    email: 'ritu@zeal.com',
    category: ConsultantCategory.PSYCHOLOGIST,
    specialties: ['CBT', 'Anxiety', 'Depression'],
    languages: ['Hindi', 'English'],
    bio: 'CBT specialist helping with anxiety and depression.',
    perMinuteRate: 85,
    faith: Faith.HINDU,
    availability: {
      monday: [{ start: '11:00', end: '19:00' }],
      tuesday: [{ start: '11:00', end: '19:00' }],
      wednesday: [{ start: '11:00', end: '19:00' }],
      thursday: [{ start: '11:00', end: '19:00' }],
      friday: [{ start: '11:00', end: '19:00' }],
      saturday: [{ start: '10:00', end: '14:00' }],
      sunday: [],
    },
  },
  {
    name: 'Dr. Sunil Reddy',
    username: 'dr_sunil',
    email: 'sunil@zeal.com',
    category: ConsultantCategory.PSYCHOLOGIST,
    specialties: ['Mindfulness', 'Life Coaching'],
    languages: ['English', 'Telugu'],
    bio: 'Psychologist and life coach focusing on personal growth.',
    perMinuteRate: 90,
    faith: Faith.OTHER,
    availability: {
      monday: [{ start: '08:00', end: '16:00' }],
      tuesday: [{ start: '08:00', end: '16:00' }],
      wednesday: [{ start: '08:00', end: '16:00' }],
      thursday: [{ start: '08:00', end: '16:00' }],
      friday: [{ start: '08:00', end: '16:00' }],
      saturday: [{ start: '09:00', end: '12:00' }],
      sunday: [],
    },
  },
  {
    name: 'Dr. Anjali Menon',
    username: 'dr_anjali',
    email: 'anjali@zeal.com',
    category: ConsultantCategory.PSYCHOLOGIST,
    specialties: ['CBT', 'Anxiety', 'Depression'],
    languages: ['English', 'Tamil'],
    bio: 'Clinical psychologist with 10+ years of experience.',
    perMinuteRate: 80,
    faith: Faith.CHRISTIAN,
    availability: {
      monday: [{ start: '10:00', end: '18:00' }],
      tuesday: [{ start: '10:00', end: '18:00' }],
      wednesday: [{ start: '10:00', end: '18:00' }],
      thursday: [{ start: '10:00', end: '18:00' }],
      friday: [{ start: '10:00', end: '18:00' }],
      saturday: [{ start: '09:00', end: '13:00' }],
      sunday: [],
    },
  },
  // Tarot Readers (5)
  {
    name: 'Sana Khan',
    username: 'sana_tarot',
    email: 'sana.tarot@zeal.com',
    category: ConsultantCategory.TAROT,
    specialties: ['Rider-Waite', 'Lenormand'],
    languages: ['Hindi', 'English'],
    bio: 'Intuitive tarot reader with 8+ years of experience.',
    perMinuteRate: 60,
    faith: Faith.ISLAM,
    availability: {
      monday: [{ start: '10:00', end: '18:00' }],
      tuesday: [{ start: '10:00', end: '18:00' }],
      wednesday: [{ start: '10:00', end: '18:00' }],
      thursday: [{ start: '10:00', end: '18:00' }],
      friday: [{ start: '10:00', end: '18:00' }],
      saturday: [{ start: '09:00', end: '13:00' }],
      sunday: [],
    },
  },
  {
    name: 'Rahul Das',
    username: 'rahul_tarot',
    email: 'rahul@zeal.com',
    category: ConsultantCategory.TAROT,
    specialties: ['Osho Zen', 'Angel Cards'],
    languages: ['Hindi', 'English'],
    bio: 'Tarot reader focusing on spiritual guidance and self-discovery.',
    perMinuteRate: 55,
    faith: Faith.HINDU,
    availability: {
      monday: [{ start: '09:00', end: '17:00' }],
      tuesday: [{ start: '09:00', end: '17:00' }],
      wednesday: [{ start: '09:00', end: '17:00' }],
      thursday: [{ start: '09:00', end: '17:00' }],
      friday: [{ start: '09:00', end: '17:00' }],
      saturday: [],
      sunday: [],
    },
  },
  {
    name: 'Kavya Iyer',
    username: 'kavya_tarot',
    email: 'kavya@zeal.com',
    category: ConsultantCategory.TAROT,
    specialties: ['Rider-Waite', 'Marseille'],
    languages: ['English', 'Tamil'],
    bio: 'Professional tarot reader with 6+ years of experience.',
    perMinuteRate: 65,
    faith: Faith.HINDU,
    availability: {
      monday: [{ start: '11:00', end: '19:00' }],
      tuesday: [{ start: '11:00', end: '19:00' }],
      wednesday: [{ start: '11:00', end: '19:00' }],
      thursday: [{ start: '11:00', end: '19:00' }],
      friday: [{ start: '11:00', end: '19:00' }],
      saturday: [{ start: '10:00', end: '14:00' }],
      sunday: [],
    },
  },
  {
    name: 'Nisha Shah',
    username: 'nisha_tarot',
    email: 'nisha@zeal.com',
    category: ConsultantCategory.TAROT,
    specialties: ['Lenormand', 'Angel Cards'],
    languages: ['Hindi', 'English'],
    bio: 'Tarot reader helping with relationships and career.',
    perMinuteRate: 58,
    faith: Faith.OTHER,
    availability: {
      monday: [{ start: '08:00', end: '16:00' }],
      tuesday: [{ start: '08:00', end: '16:00' }],
      wednesday: [{ start: '08:00', end: '16:00' }],
      thursday: [{ start: '08:00', end: '16:00' }],
      friday: [{ start: '08:00', end: '16:00' }],
      saturday: [],
      sunday: [],
    },
  },
  {
    name: 'Prakash Reddy',
    username: 'prakash_tarot',
    email: 'prakash@zeal.com',
    category: ConsultantCategory.TAROT,
    specialties: ['Rider-Waite', 'Osho Zen'],
    languages: ['Telugu', 'English'],
    bio: 'Tarot reader and spiritual healer.',
    perMinuteRate: 52,
    faith: Faith.HINDU,
    availability: {
      monday: [{ start: '10:00', end: '18:00' }],
      tuesday: [{ start: '10:00', end: '18:00' }],
      wednesday: [{ start: '10:00', end: '18:00' }],
      thursday: [{ start: '10:00', end: '18:00' }],
      friday: [{ start: '10:00', end: '18:00' }],
      saturday: [{ start: '09:00', end: '13:00' }],
      sunday: [],
    },
  },
  // Numerologists (5)
  {
    name: 'Dr. Anjali Mathur',
    username: 'anjali_numerology',
    email: 'anjali.num@zeal.com',
    category: ConsultantCategory.NUMEROLOGIST,
    specialties: ['Chaldean', 'Pythagorean'],
    languages: ['Hindi', 'English'],
    bio: 'Numerologist with 10+ years of experience.',
    perMinuteRate: 70,
    faith: Faith.HINDU,
    availability: {
      monday: [{ start: '10:00', end: '18:00' }],
      tuesday: [{ start: '10:00', end: '18:00' }],
      wednesday: [{ start: '10:00', end: '18:00' }],
      thursday: [{ start: '10:00', end: '18:00' }],
      friday: [{ start: '10:00', end: '18:00' }],
      saturday: [{ start: '09:00', end: '13:00' }],
      sunday: [],
    },
  },
  {
    name: 'Raj Kumar',
    username: 'raj_num',
    email: 'raj.num@zeal.com',
    category: ConsultantCategory.NUMEROLOGIST,
    specialties: ['Kabbalah', 'Indian'],
    languages: ['Hindi', 'English'],
    bio: 'Numerologist specializing in destiny mapping.',
    perMinuteRate: 65,
    faith: Faith.HINDU,
    availability: {
      monday: [{ start: '09:00', end: '17:00' }],
      tuesday: [{ start: '09:00', end: '17:00' }],
      wednesday: [{ start: '09:00', end: '17:00' }],
      thursday: [{ start: '09:00', end: '17:00' }],
      friday: [{ start: '09:00', end: '17:00' }],
      saturday: [],
      sunday: [],
    },
  },
  {
    name: 'Sneha Reddy',
    username: 'sneha_num',
    email: 'sneha.num@zeal.com',
    category: ConsultantCategory.NUMEROLOGIST,
    specialties: ['Pythagorean', 'Chinese'],
    languages: ['Telugu', 'English'],
    bio: 'Numerologist helping with life path decisions.',
    perMinuteRate: 60,
    faith: Faith.HINDU,
    availability: {
      monday: [{ start: '11:00', end: '19:00' }],
      tuesday: [{ start: '11:00', end: '19:00' }],
      wednesday: [{ start: '11:00', end: '19:00' }],
      thursday: [{ start: '11:00', end: '19:00' }],
      friday: [{ start: '11:00', end: '19:00' }],
      saturday: [{ start: '10:00', end: '14:00' }],
      sunday: [],
    },
  },
  {
    name: 'Vivek Singh',
    username: 'vivek_num',
    email: 'vivek.num@zeal.com',
    category: ConsultantCategory.NUMEROLOGIST,
    specialties: ['Chaldean', 'Indian'],
    languages: ['Hindi', 'English'],
    bio: 'Numerologist with 8+ years of experience.',
    perMinuteRate: 55,
    faith: Faith.SIKH,
    availability: {
      monday: [{ start: '08:00', end: '16:00' }],
      tuesday: [{ start: '08:00', end: '16:00' }],
      wednesday: [{ start: '08:00', end: '16:00' }],
      thursday: [{ start: '08:00', end: '16:00' }],
      friday: [{ start: '08:00', end: '16:00' }],
      saturday: [],
      sunday: [],
    },
  },
  {
    name: 'Priya Sharma',
    username: 'priya_num',
    email: 'priya.num@zeal.com',
    category: ConsultantCategory.NUMEROLOGIST,
    specialties: ['Kabbalah', 'Pythagorean'],
    languages: ['Hindi', 'English'],
    bio: 'Numerologist focusing on personal growth and success.',
    perMinuteRate: 62,
    faith: Faith.HINDU,
    availability: {
      monday: [{ start: '10:00', end: '18:00' }],
      tuesday: [{ start: '10:00', end: '18:00' }],
      wednesday: [{ start: '10:00', end: '18:00' }],
      thursday: [{ start: '10:00', end: '18:00' }],
      friday: [{ start: '10:00', end: '18:00' }],
      saturday: [{ start: '09:00', end: '13:00' }],
      sunday: [],
    },
  },
  // Healers (5)
  {
    name: 'Ananya Gupta',
    username: 'ananya_healer',
    email: 'ananya@zeal.com',
    category: ConsultantCategory.HEALER,
    specialties: ['Reiki', 'Pranic'],
    languages: ['Hindi', 'English'],
    bio: 'Reiki master and energy healer with 10+ years of experience.',
    perMinuteRate: 80,
    faith: Faith.HINDU,
    availability: {
      monday: [{ start: '10:00', end: '18:00' }],
      tuesday: [{ start: '10:00', end: '18:00' }],
      wednesday: [{ start: '10:00', end: '18:00' }],
      thursday: [{ start: '10:00', end: '18:00' }],
      friday: [{ start: '10:00', end: '18:00' }],
      saturday: [{ start: '09:00', end: '13:00' }],
      sunday: [],
    },
  },
  {
    name: 'Manoj Kumar',
    username: 'manoj_healer',
    email: 'manoj@zeal.com',
    category: ConsultantCategory.HEALER,
    specialties: ['Crystal', 'Sound'],
    languages: ['Hindi', 'English'],
    bio: 'Energy healer using crystals and sound therapy.',
    perMinuteRate: 75,
    faith: Faith.OTHER,
    availability: {
      monday: [{ start: '09:00', end: '17:00' }],
      tuesday: [{ start: '09:00', end: '17:00' }],
      wednesday: [{ start: '09:00', end: '17:00' }],
      thursday: [{ start: '09:00', end: '17:00' }],
      friday: [{ start: '09:00', end: '17:00' }],
      saturday: [],
      sunday: [],
    },
  },
  {
    name: 'Radhika Iyer',
    username: 'radhika_healer',
    email: 'radhika@zeal.com',
    category: ConsultantCategory.HEALER,
    specialties: ['Reiki', 'Energy'],
    languages: ['Tamil', 'English'],
    bio: 'Reiki healer focusing on chakra balancing.',
    perMinuteRate: 70,
    faith: Faith.HINDU,
    availability: {
      monday: [{ start: '11:00', end: '19:00' }],
      tuesday: [{ start: '11:00', end: '19:00' }],
      wednesday: [{ start: '11:00', end: '19:00' }],
      thursday: [{ start: '11:00', end: '19:00' }],
      friday: [{ start: '11:00', end: '19:00' }],
      saturday: [{ start: '10:00', end: '14:00' }],
      sunday: [],
    },
  },
  {
    name: 'Suresh Nair',
    username: 'suresh_healer',
    email: 'suresh@zeal.com',
    category: ConsultantCategory.HEALER,
    specialties: ['Pranic', 'Crystal'],
    languages: ['Malayalam', 'English'],
    bio: 'Pranic healer with 8+ years of experience.',
    perMinuteRate: 65,
    faith: Faith.HINDU,
    availability: {
      monday: [{ start: '08:00', end: '16:00' }],
      tuesday: [{ start: '08:00', end: '16:00' }],
      wednesday: [{ start: '08:00', end: '16:00' }],
      thursday: [{ start: '08:00', end: '16:00' }],
      friday: [{ start: '08:00', end: '16:00' }],
      saturday: [],
      sunday: [],
    },
  },
  {
    name: 'Neha Shah',
    username: 'neha_healer',
    email: 'neha@zeal.com',
    category: ConsultantCategory.HEALER,
    specialties: ['Reiki', 'Sound'],
    languages: ['Hindi', 'English'],
    bio: 'Reiki healer using sound therapy for holistic healing.',
    perMinuteRate: 72,
    faith: Faith.OTHER,
    availability: {
      monday: [{ start: '10:00', end: '18:00' }],
      tuesday: [{ start: '10:00', end: '18:00' }],
      wednesday: [{ start: '10:00', end: '18:00' }],
      thursday: [{ start: '10:00', end: '18:00' }],
      friday: [{ start: '10:00', end: '18:00' }],
      saturday: [{ start: '09:00', end: '13:00' }],
      sunday: [],
    },
  },
];
